authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<int:id>', views.delete, name='delete')
]

books/urls.py
from django.urls import path
from books import views

app_name = 'books'

urlpatterns = [
    path('create/', views.create, name='create-obj'),
    path('', views.get, name='get-obj'),
    path('<int:id>/', views.get_detail, name='get-one-obj'),
    path('delete/<int:id>/', views.delete, name='delete-obj'),
    path('update/<int:id>/', views.update, name='update-obj')
]

reader_books_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('pdf/', include('pdf_books.urls')),
    path('authors/', include('authors.urls')),
    path('authenticate/', include('authenticate.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authors/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    # portrait
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

authors/forms.py
from dataclasses import field
from django import forms
from .models import Author

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'date_of_birth']

authors/views.py
from django.shortcuts import render, redirect
from .forms import AuthorForm
from .models import Author

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect('books:get-obj')
    if not request.user.is_staff:
        return redirect('books:get-obj')
    authors = Author.objects.all()
    form = AuthorForm()
    return render(request, 'authors/index.html', { 'authors': authors, 'form': form })

def create(request):
    if not request.user.is_authenticated:
        return redirect('books:get-obj')
    if not request.user.is_staff:
        return redirect('books:get-obj')
    form = AuthorForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('authors:index')

def delete(request, id):
    if not request.user.is_authenticated:
        return redirect('books:get-obj')
    if not request.user.is_staff:
        return redirect('books:get-obj')
    author = Author.objects.get(pk=id)
    author.delete()
    return redirect('authors:index')

authors/templates/authors/index.html
{% extends 'books/base.html' %}

{% block content %}
<form action="{% url 'authors:create' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% if authors %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
            </tr>
        </thead>
        <tbody>
            {% for author in authors %}
                <tr>
                    <td>{{ author.first_name }}</td>
                    <td>{{ author.last_name }}</td>
                    <td>{{ author.date_of_birth }}</td>
                    <td><a class="btn btn-primary" href="{% url 'authors:delete' id=author.id %}" role="button">Delete</a></td>
                </tr>
                <p></p>
            {% endfor %}
        </tbody>
    </table>
{% else %}
Emply list
{% endif %}

{% endblock %}