books/urls.py
from django.urls import path
from books import views

app_name = 'books'

urlpatterns = [
    path('create/', views.create, name='create-obj'),
    path('', views.get, name='get-obj'),
    path('<int:id>/', views.get_detail, name='get-one-obj'),
    path('delete/<int:id>/', views.delete, name='delete-obj'),
    path('update/<int:id>/', views.update, name='update-obj')
]

pdf_books/urls.py
from django.urls import path
from . import views

app_name = 'pdf_books'

urlpatterns = [
    path('<int:id>/', views.get_book, name='get_book'),
    path('create/<int:id>/', views.create, name='create_note'),
    path('delete/<int:id>/', views.delete, name='delete_note'),
    path('download/<int:id>/', views.download_book, name='download_book')
]

reader_books_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('pdf/', include('pdf_books.urls')),
    path('authors/', include('authors.urls')),
    path('authenticate/', include('authenticate.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdf_books/models.py
from django.db import models
from django.contrib.auth.models import User
from books.models import Book

# Create your models here.
class Notes(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    num_page = models.IntegerField()
    description = models.CharField(max_length=255)

pdf_books/forms.py
from django import forms
from .models import Notes

class NoteForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['num_page', 'description']

pdf_books/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import redirect, render
from books.models import Book
# from reader_books_website.settings import BASE_DIR
from .forms import NoteForm
from .models import Notes
import os

def download_book(request, id):
    book = Book.objects.get(pk=id)
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    file_path = BASE_DIR + book.file.url

    if os.path.exists(file_path):
        with open(file_path, 'rb') as fl:
            response = HttpResponse(fl.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response

    return redirect('books:get-obj')

def get_book(request, id):
    if not request.user.is_authenticated:
        return redirect('books:get-obj')
    book = Book.objects.get(pk = id)
    notes = Notes.objects.filter(user=request.user, book=book)
    form = NoteForm()
    return render(request, 'pdf_books/reader.html', 
    { 
        'book': book, 
        'form': form,
        'notes': notes
    })

def create(request, id):
    if not request.user.is_authenticated:
        return redirect('books:get-obj')
    form = NoteForm(request.POST)
    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.book = Book.objects.get(pk=id)
        form.save()
    return redirect('pdf_books:get_book', id=id)


def delete(request, id):
    if not request.user.is_authenticated:
        return redirect('books:get-obj')
    
    note = Notes.objects.get(pk=id)

    if not note.user == request.user:
        return redirect('books:get-obj')
    
    note.delete()
    return redirect('pdf_books:get_book', id=note.book.id)

pdf_books/templates/pdf_books/reader.html
{% extends 'books/base.html' %}

{% block content %}
<div class="row">
    <div class="col-7">
        <iframe src="{{book.file.url}}" width="100%" height="700px">
        </iframe>
    </div>
    <div class="col">
        <h1>FUNCTIONS</h1>
        
        <form action="{% url 'pdf_books:create_note' id=book.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Number of page</label>
                {{form.num_page}}
            </div>
            <div class="form-group">
                <label>Description</label>
                {{form.description}}
            </div>
            <input type="submit" value="Submit">
        </form>

        {% if notes %}
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Page</th>
                    <th scope="col">Desc</th>
                    <th scope="col">Func</th>
                </tr>
                </thead>
                <tbody>
                    {% for note in notes %}
                        <tr>
                            <td>{{ note.num_page }}</td>
                            <td>{{ note.description }}</td>
                            <td><a href="{% url 'pdf_books:delete_note' id=note.id %}" class="btn btn-primary">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
        
    </div>
</div>

{% endblock %}