authenticate/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout')
]

authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<int:id>', views.delete, name='delete')
]

books/urls.py
from django.urls import path
from books import views

app_name = 'books'

urlpatterns = [
    path('create/', views.create, name='create-obj'),
    path('', views.get, name='get-obj'),
    path('<int:id>/', views.get_detail, name='get-one-obj'),
    path('delete/<int:id>/', views.delete, name='delete-obj'),
    path('update/<int:id>/', views.update, name='update-obj')
]

pdf_books/urls.py
from django.urls import path
from . import views

app_name = 'pdf_books'

urlpatterns = [
    path('<int:id>/', views.get_book, name='get_book'),
    path('create/<int:id>/', views.create, name='create_note'),
    path('delete/<int:id>/', views.delete, name='delete_note'),
    path('download/<int:id>/', views.download_book, name='download_book')
]

reader_books_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('pdf/', include('pdf_books.urls')),
    path('authors/', include('authors.urls')),
    path('authenticate/', include('authenticate.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import User
from authors.models import Author

class Book(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    name_of_book = models.CharField(max_length=255)
    date_of_release = models.DateField()
    author = models.ForeignKey(Author, blank=True, null=True, on_delete=models.CASCADE)
    description = models.TextField()
    file = models.FileField(upload_to='books/', blank=True, null=True)
    cover = models.ImageField(upload_to='images/', blank=True, null=True)

books/forms.py
from django import forms
from books.models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['user', 'name_of_book', 'date_of_release', 'author', 'description', 'file', 'cover']

books/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from books.models import Book
from authors.models import Author
from .forms import BookForm

cyrillic = {
    'а': 'a', 'А': 'a',
    'б': 'b', 'Б': 'b', 
    'в': 'v', 'В': 'v', 
    'г': 'g', 'Г': 'g',
    'д': 'd', 'Д': 'd',
    'е': 'e', 'Е': 'e',
    'ё': 'e', 'Ё': 'e', 
    'ж': 'zh', 'Ж': 'zh',
    'з': 'z', 'З': 'z', 
    'и': 'i', 'И': 'i',
    'й': 'i', 'Й': 'i',
    'к': 'k', 'К': 'k', 
    'л': 'l', 'Л': 'l',
    'м': 'm', 'М': 'm',
    'н': 'n', 'Н': 'n',
    'о': 'o', 'О': 'o', 
    'п': 'p', 'П': 'p', 
    'р': 'r', 'Р': 'r', 
    'с': 's', 'С': 's',
    'т': 't', 'Т': 't',
    'у': 'u', 'У': 'u', 
    'ф': 'f', 'Ф': 'f', 
    'х': 'h', 'Х': 'h', 
    'ц': 'ts', 'Ц': 'ts', 
    'ч': 'ch', 'Ч': 'ch',
    'ш': 'sh', 'Ш': 'sh', 
    'щ': 'sh', 'Щ': 'sh', 
    'ъ': '', 'Ъ': '', 
    'ь': '', 'Ь': '', 
    'ы': 'i', 'Ы': 'i',
    'э': 'e', 'Э': 'e', 
    'ю': 'yu', 'Ю': 'yu',
    'я': 'ya', 'Я': 'ya',
}

def change_char(word):
    new_word = ''
    
    for i in word:
        char = i
        if i in cyrillic.keys():
            char = cyrillic[i]
        new_word += char
    
    return new_word

def get(request):
    books = Book.objects.all()
    return render(request, 'books/index.html', { 'books': books })

def get_detail(request, id):
    book = Book.objects.get(pk=id)
    return render(request, 'books/detail.html', { 'book': book })

def update(request, id):
    book = Book.objects.get(pk=id)

    if not request.user.is_authenticated:
        return redirect('books:get-obj')
    if not book.user == request.user:
        return redirect('books:get-obj')

    if request.method == 'POST':
        cover = request.POST.get('cover')
        file = request.POST.get('file')
        author = request.POST.get('author')

        if author != '':
            book.author = Author.objects.get(pk=author)    
        if file != '':
            request.FILES['file'].name = change_char(request.FILES['file'].name)
            book.file = request.FILES['file']
        if cover != '':
            book.cover = request.FILES['cover']
        
        book.name_of_book = request.POST.get('name_of_book')
        book.date_of_release = request.POST.get('date_of_release')
        book.description = request.POST.get('description')
        
        book.save()

        return redirect('books:get-one-obj', id=id)
    else:
        form = BookForm(initial={
                    'name_of_book': book.name_of_book, 
                    'date_of_release': book.date_of_release, 
                    'description': book.description,
                    'author': book.author,
                }
            )
    
    return render(request, 'books/update.html', { 'form': form, 'book_id': id })

def create(request):
    if not request.user.is_authenticated:
        return redirect('books:get-obj')

    if request.method == 'POST':
        
        request.FILES['file'].name = change_char(request.FILES['file'].name)

        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.user = request.user
            book.save()
            return redirect('books:get-obj')
    else:
        form = BookForm()
        
    return render(request, 'books/create.html', { 'form': form })

def delete(request, id):
    book = Book.objects.get(pk = id)
    
    if not book.user == request.user:
        return redirect('books:get-obj')
    if not request.user.is_authenticated:
        return redirect('books:get-obj')
    
    book.delete()
    return redirect('books:get-obj')

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Book reader</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    {% include 'books/nav_bar.html' %}
    <div class='container'>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

books/templates/books/create.html
{% extends 'books/base.html' %}

{% block content %}
<form action="{% url 'books:create-obj' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Name of book</label>
        {{form.name_of_book}}
    </div>
    <div class="form-group">
        <label>Date of release</label>
        {{form.date_of_release}}
    </div>
    <div class="form-group">
        <label>Author</label>
        {{form.author}}
    </div>
    <div class="form-group">
        <label>Description</label>
        {{form.description}}
    </div>
    <div class="form-group">
        <label>File</label>
        {{form.file}}
    </div>
    <div class="form-group">
        <label>Cover</label>
        {{form.cover}}
    </div>
    <input type="submit" value="Submit">
</form>
{% endblock %}

books/templates/books/detail.html
{% extends 'books/base.html' %}

{% block content %}

<div class="row gx-5">
    <div class="col-4">
        <img src="{{ book.cover.url }}" style="width: 430px; height: 600px;" alt="...">
    </div>
    <div class="col-8">
        <h1>{{book.name_of_book}}</h1>

        {% if book.author %}
            <h4 class="text-muted">{{book.author}}</h4>
        {% else %}
            <h4 class="text-muted">No author</h4>
        {% endif %}
        
        <p class="text-muted">{{book.date_of_release}}</p>
        <p>{{book.description}}</p>

        {% if user.is_authenticated %}
            <div class="row">
                <div class="d-grid gap-2 col-3">
                    <a href="{% url 'pdf_books:get_book' id=book.id %}" class="btn btn-primary m-2">Read book</a>
                </div>
                <div class="d-grid gap-2 col-3">
                    <a href="{% url 'pdf_books:download_book' id=book.id %}" class="btn btn-primary m-2">Download book</a>
                </div>
            </div>
            
            {% if book.user == user %}
                <div class="row">
                    <div class="col">
                        <div class="d-grid gap-2">
                            <a href="{% url 'books:delete-obj' id=book.id %}" class="btn btn-primary">Delete</a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="d-grid gap-2">
                            <a href="{% url 'books:update-obj' id=book.id %}" class="btn btn-primary">Update</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}

books/templates/books/index.html
{% extends 'books/base.html' %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for book in books%}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.name_of_book }}</h5>
                    </div>
                    <img src="{{ book.cover.url }}" class="card-img-bottom" height="700px" alt="...">
                    <a href="{% url 'books:get-one-obj' id=book.id %}" class="btn btn-primary m-2">Detail of book</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

books/templates/books/nav_bar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'books:get-obj' %}">
            <img src="{% static 'books/book_logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            BookReader
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'books:get-obj' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'books:create-obj' %}">Create book</a>
                </li>

                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authors:index' %}">Add author</a>
                    </li>
                {% endif %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        </div>
    </div>
</nav>

books/templates/books/update.html
{% extends 'books/base.html' %}

{% block content %}
<form action="{% url 'books:update-obj' id=book_id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Name of book</label>
        {{form.name_of_book}}
    </div>
    <div class="form-group">
        <label>Date of release</label>
        {{form.date_of_release}}
    </div>
    <div class="form-group">
        <label>Author</label>
        {{form.author}}
    </div>
    <div class="form-group">
        <label>Description</label>
        {{form.description}}
    </div>
    <div class="form-group">
        <label>File</label>
        {{form.file}}
    </div>
    <div class="form-group">
        <label>Cover</label>
        {{form.cover}}
    </div>
    <input type="submit" value="Submit">
</form>
{% endblock %}